package com.example.ktor

import com.example.domain.models.UpdateUser
import com.example.domain.models.UpdateVehicle
import com.example.domain.models.LoginRequest
import com.example.domain.models.User
import com.example.domain.models.Vehicle
import com.example.domain.usecase.ProviderUseCase
import org.mindrot.jbcrypt.BCrypt
import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.http.content.*
import io.ktor.server.routing.*
import io.ktor.server.auth.*
import io.ktor.http.content.PartData
import io.ktor.http.content.forEachPart
import io.ktor.utils.io.jvm.javaio.toInputStream
import com.example.domain.security.JwtConfig
import java.io.File
fun Application.configureRouting() {
    routing {
        get("/") {
            call.respondText("Vehicle API is running!")
        }
        
        get("/health") {
            call.respond(mapOf("status" to "ok"))
        }

        // Static plugin
        staticResources("/static", "static")

        // Global Vehicles (Marketplace)
        route("/vehicles") {
            get {
                call.respond(ProviderUseCase.getAllVehicles())
            }
        }

        // LOGIN & REGISTER
        post("/login") {
            try {
                val loginRequest = call.receive<LoginRequest>()
                val email = loginRequest.email
                val password = loginRequest.password
                
                call.application.environment.log.info("Login attempt for email: $email")
                val user = ProviderUseCase.getUserByEmail(email)
                if (user != null) {
                        call.application.environment.log.info("User found: ${user.username}")
                        if (BCrypt.checkpw(password, user.password)) {
                            call.application.environment.log.info("Password match!")
                            val token = JwtConfig.generateToken(user.email)
                                
                            val userResponse = User(
                                id = user.id,
                                username = user.username,
                                email = user.email,
                                password = user.password,
                                description = user.description,
                                phone = user.phone,
                                urlImage = user.urlImage,
                                active = user.active,
                                token = token,
                                role = user.role
                            )
                            // Optionally update the token in DB if needed by front-end:
                            ProviderUseCase.updateUser(UpdateUser(token = token), user.id)
                            call.respond(userResponse)
                        } else {
                            call.application.environment.log.warn("Password mismatch for user: ${user.username}")
                            call.respond(HttpStatusCode.Unauthorized, "Invalid credentials")
                        }
                } else {
                    call.application.environment.log.warn("User not found for email: $email")
                    call.respond(HttpStatusCode.Unauthorized, "Invalid credentials")
                }
            } catch (e: Exception) {
                call.application.environment.log.error("Login error: ${e.message}", e)
                call.respond(HttpStatusCode.BadRequest, "Invalid request body")
            }
        }

        post("/register") {
            // Register expects User object. ID might be generated by client or server?
            // UserTable: id is varchar. User model has 'id'.
            // If client sends ID, use it. If not, generate UUID?
            // Provided User model has 'id' non-nullable. 
            // So client SHOULD send id (e.g. UUID).
            try {
                val user = call.receive<User>()
                if (ProviderUseCase.getUserByEmail(user.email) != null) {
                    call.respond(HttpStatusCode.Conflict, "Email already exists")
                } else {
                    if (ProviderUseCase.insertUser(user)) {
                        call.respond(HttpStatusCode.Created, user)
                    } else {
                        call.respond(HttpStatusCode.InternalServerError, "Failed to register")
                    }
                }
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Invalid User data: ${e.message}")
            }
        }

        // UPLOAD ENDPOINT
        post("/upload/{id}") {
            val dni = call.parameters["id"] ?: return@post call.respond(HttpStatusCode.BadRequest, "ID missing")
            val user = ProviderUseCase.getUserById(dni) ?: return@post call.respond(HttpStatusCode.NotFound, "User not found")
            
            var imageUrl = ""
            val uploadDir = File("upload/images/$dni")
            if (!uploadDir.exists()) uploadDir.mkdirs()

            try {
                val multipart = call.receiveMultipart()
                multipart.forEachPart { part ->
                    if (part is PartData.FileItem) {
                        val originalName = part.originalFileName ?: "image.jpg"
                        val ext = File(originalName).extension.takeIf { it.isNotEmpty() } ?: "jpg"
                        val fileName = "profile_${System.currentTimeMillis()}.$ext"
                        val file = File(uploadDir, fileName)
                        
                        part.provider().toInputStream().use { input ->
                            file.outputStream().buffered().use { output ->
                                input.copyTo(output)
                            }
                        }
                        // Set standard URL prefix (Ktor should serve 'upload' statically if configured, we'll map below)
                        imageUrl = "/upload/images/$dni/$fileName"
                    }
                    part.dispose()
                }

                if (imageUrl.isNotEmpty()) {
                    // Update user in DB with new imageUrl
                    ProviderUseCase.updateUser(UpdateUser(urlImage = imageUrl), dni)
                    call.respond(HttpStatusCode.OK, mapOf("urlImage" to imageUrl))
                } else {
                    call.respond(HttpStatusCode.BadRequest, "No file uploaded")
                }
            } catch (e: Exception) {
                call.application.environment.log.error("Upload error: ${e.message}", e)
                call.respond(HttpStatusCode.InternalServerError, "Error processing upload")
            }
        }

        authenticate("auth-jwt") {
            route("/users") {
            get {
                call.respond(ProviderUseCase.getAllUsers())
            }

            get("/{id}") {
                val id = call.parameters["id"] ?: return@get call.respond(HttpStatusCode.BadRequest)
                val user = ProviderUseCase.getUserById(id)
                if (user != null) call.respond(user) else call.respond(HttpStatusCode.NotFound)
            }

            put("/{id}") {
                val id = call.parameters["id"] ?: return@put call.respond(HttpStatusCode.BadRequest)
                val update = call.receive<UpdateUser>()
                if (ProviderUseCase.updateUser(update, id)) {
                    call.respond(HttpStatusCode.OK, "User updated")
                } else {
                    call.respond(HttpStatusCode.NotFound)
                }
            }

            delete("/{id}") {
                val id = call.parameters["id"] ?: return@delete call.respond(HttpStatusCode.BadRequest)
                if (ProviderUseCase.deleteUser(id)) {
                    call.respond(HttpStatusCode.OK, "User deleted")
                } else {
                    call.respond(HttpStatusCode.NotFound)
                }
            }

            // Vehicles per User
            route("/{userId}/vehicles") {
                get {
                    val userId = call.parameters["userId"] ?: return@get call.respond(HttpStatusCode.BadRequest)
                    val vehicles = ProviderUseCase.getVehiclesByUserId(userId)
                    call.respond(vehicles)
                }
                
                post {
                    val userId = call.parameters["userId"] ?: return@post call.respond(HttpStatusCode.BadRequest)
                    // We expect Vehicle body. Vehicle has userId field.
                    // We should verify body.userId matches path userId or override it.
                    try {
                        val vehicle = call.receive<Vehicle>()
                        if (vehicle.userId != userId) {
                            call.respond(HttpStatusCode.BadRequest, "UserId in path and body mismatch")
                            return@post
                        }
                        if (ProviderUseCase.insertVehicle(vehicle)) {
                            call.respond(HttpStatusCode.Created, "Vehicle created")
                        } else {
                            call.respond(HttpStatusCode.Conflict)
                        }
                    } catch (e: Exception) {
                        call.respond(HttpStatusCode.BadRequest, "Invalid Vehicle data: ${e.message}")
                    }
                }

                delete {
                    val userId = call.parameters["userId"] ?: return@delete call.respond(HttpStatusCode.BadRequest)
                    if (ProviderUseCase.deleteVehiclesByUserId(userId)) {
                         call.respond(HttpStatusCode.OK, "All user vehicles deleted")
                    } else {
                        call.respond(HttpStatusCode.NotFound, "No vehicles found for user")
                    }
                }
                
                // Single Vehicle operations under User
                // Note: Standard hierarchy usually /users/{uid}/vehicles/{vid}
                route("/{vehicleId}") {
                     get {
                         // Mostrar un elemento de un usuario
                         val userId = call.parameters["userId"]!!
                         val vehicleId = call.parameters["vehicleId"]!!
                         val vehicle = ProviderUseCase.getVehicleById(vehicleId)
                         if (vehicle != null && vehicle.userId == userId) {
                             call.respond(vehicle)
                         } else {
                             call.respond(HttpStatusCode.NotFound)
                         }
                     }
                     
                     put {
                         val userId = call.parameters["userId"]!!
                         val vehicleId = call.parameters["vehicleId"]!!
                         val update = call.receive<UpdateVehicle>()
                         // Verify ownership?
                         val existing = ProviderUseCase.getVehicleById(vehicleId)
                         if (existing != null && existing.userId == userId) {
                             if (ProviderUseCase.updateVehicle(update, vehicleId)) {
                                 call.respond(HttpStatusCode.OK, "Vehicle updated")
                             } else {
                                 call.respond(HttpStatusCode.InternalServerError)
                             }
                         } else {
                             call.respond(HttpStatusCode.NotFound)
                         }
                     }

                     delete {
                         val userId = call.parameters["userId"]!!
                         val vehicleId = call.parameters["vehicleId"]!!
                         val existing = ProviderUseCase.getVehicleById(vehicleId)
                         if (existing != null && existing.userId == userId) {
                              if (ProviderUseCase.deleteVehicle(vehicleId)) {
                                  call.respond(HttpStatusCode.OK, "Vehicle deleted")
                              } else {
                                  call.respond(HttpStatusCode.InternalServerError)
                              }
                         } else {
                             call.respond(HttpStatusCode.NotFound)
                         }
                     }
                }
            }
                }
        }
    }
}
