package com.example.ktor

import com.example.domain.models.UpdateUser
import com.example.domain.models.UpdateVehicle
import com.example.domain.models.User
import com.example.domain.models.Vehicle
import com.example.domain.usecase.ProviderUseCase
import org.mindrot.jbcrypt.BCrypt
import io.ktor.http.*
import io.ktor.server.application.*
import io.ktor.server.request.*
import io.ktor.server.response.*
import io.ktor.server.http.content.*
import io.ktor.server.routing.*

fun Application.configureRouting() {
    routing {
        get("/") {
            call.respondText("Vehicle API is running!")
        }
        
        get("/health") {
            call.respond(mapOf("status" to "ok"))
        }

        // Static plugin
        staticResources("/static", "static")

        // LOGIN & REGISTER
        post("/login") {
            val credentials = call.receive<User>() // Or a LoginRequest DTO, but usually simpler to reuse User or Map
            // Actually, receive Map<String, String> is safer if User has non-nullable fields required like id
            // But User model has 'id' which is not present in login request usually.
            // Let's assume client sends partial json or I should use a DTO.
            // For simplicity, let's try to parse as Map first or checks.
            // Wait, Kotlin Serialization needs matching fields.
            // If I use User, fields like 'id', 'username', etc might be required.
            // Better to use specific login DTO or Map.
            // Let's use Map.
            try {
                // Since I didn't create LoginDTO, let's use a workaround or expected format
                val map = call.receive<Map<String, String>>()
                val email = map["email"]
                val password = map["password"]
                if (email != null && password != null) {
                    val user = ProviderUseCase.getUserByEmail(email)
                    if (user != null && BCrypt.checkpw(password, user.password)) {
                         call.respond(user)
                    } else {
                        call.respond(HttpStatusCode.Unauthorized, "Invalid credentials")
                    }
                } else {
                    call.respond(HttpStatusCode.BadRequest, "Missing email or password")
                }
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Invalid request body")
            }
        }

        post("/register") {
            // Register expects User object. ID might be generated by client or server?
            // UserTable: id is varchar. User model has 'id'.
            // If client sends ID, use it. If not, generate UUID?
            // Provided User model has 'id' non-nullable. 
            // So client SHOULD send id (e.g. UUID).
            try {
                val user = call.receive<User>()
                if (ProviderUseCase.getUserByEmail(user.email) != null) {
                    call.respond(HttpStatusCode.Conflict, "Email already exists")
                } else {
                    if (ProviderUseCase.insertUser(user)) {
                        call.respond(HttpStatusCode.Created, user)
                    } else {
                        call.respond(HttpStatusCode.InternalServerError, "Failed to register")
                    }
                }
            } catch (e: Exception) {
                call.respond(HttpStatusCode.BadRequest, "Invalid User data: ${e.message}")
            }
        }

        route("/users") {
            get {
                call.respond(ProviderUseCase.getAllUsers())
            }

            get("/{id}") {
                val id = call.parameters["id"] ?: return@get call.respond(HttpStatusCode.BadRequest)
                val user = ProviderUseCase.getUserById(id)
                if (user != null) call.respond(user) else call.respond(HttpStatusCode.NotFound)
            }

            put("/{id}") {
                val id = call.parameters["id"] ?: return@put call.respond(HttpStatusCode.BadRequest)
                val update = call.receive<UpdateUser>()
                if (ProviderUseCase.updateUser(update, id)) {
                    call.respond(HttpStatusCode.OK, "User updated")
                } else {
                    call.respond(HttpStatusCode.NotFound)
                }
            }

            delete("/{id}") {
                val id = call.parameters["id"] ?: return@delete call.respond(HttpStatusCode.BadRequest)
                if (ProviderUseCase.deleteUser(id)) {
                    call.respond(HttpStatusCode.OK, "User deleted")
                } else {
                    call.respond(HttpStatusCode.NotFound)
                }
            }

            // Vehicles per User
            route("/{userId}/vehicles") {
                get {
                    val userId = call.parameters["userId"] ?: return@get call.respond(HttpStatusCode.BadRequest)
                    val vehicles = ProviderUseCase.getVehiclesByUserId(userId)
                    call.respond(vehicles)
                }
                
                post {
                    val userId = call.parameters["userId"] ?: return@post call.respond(HttpStatusCode.BadRequest)
                    // We expect Vehicle body. Vehicle has userId field.
                    // We should verify body.userId matches path userId or override it.
                    try {
                        val vehicle = call.receive<Vehicle>()
                        if (vehicle.userId != userId) {
                            call.respond(HttpStatusCode.BadRequest, "UserId in path and body mismatch")
                            return@post
                        }
                        if (ProviderUseCase.insertVehicle(vehicle)) {
                            call.respond(HttpStatusCode.Created, "Vehicle created")
                        } else {
                            call.respond(HttpStatusCode.Conflict)
                        }
                    } catch (e: Exception) {
                        call.respond(HttpStatusCode.BadRequest, "Invalid Vehicle data: ${e.message}")
                    }
                }

                delete {
                    val userId = call.parameters["userId"] ?: return@delete call.respond(HttpStatusCode.BadRequest)
                    if (ProviderUseCase.deleteVehiclesByUserId(userId)) {
                         call.respond(HttpStatusCode.OK, "All user vehicles deleted")
                    } else {
                        call.respond(HttpStatusCode.NotFound, "No vehicles found for user")
                    }
                }
                
                // Single Vehicle operations under User
                // Note: Standard hierarchy usually /users/{uid}/vehicles/{vid}
                route("/{vehicleId}") {
                     get {
                         // Mostrar un elemento de un usuario
                         val userId = call.parameters["userId"]!!
                         val vehicleId = call.parameters["vehicleId"]!!
                         val vehicle = ProviderUseCase.getVehicleById(vehicleId)
                         if (vehicle != null && vehicle.userId == userId) {
                             call.respond(vehicle)
                         } else {
                             call.respond(HttpStatusCode.NotFound)
                         }
                     }
                     
                     put {
                         val userId = call.parameters["userId"]!!
                         val vehicleId = call.parameters["vehicleId"]!!
                         val update = call.receive<UpdateVehicle>()
                         // Verify ownership?
                         val existing = ProviderUseCase.getVehicleById(vehicleId)
                         if (existing != null && existing.userId == userId) {
                             if (ProviderUseCase.updateVehicle(update, vehicleId)) {
                                 call.respond(HttpStatusCode.OK, "Vehicle updated")
                             } else {
                                 call.respond(HttpStatusCode.InternalServerError)
                             }
                         } else {
                             call.respond(HttpStatusCode.NotFound)
                         }
                     }

                     delete {
                         val userId = call.parameters["userId"]!!
                         val vehicleId = call.parameters["vehicleId"]!!
                         val existing = ProviderUseCase.getVehicleById(vehicleId)
                         if (existing != null && existing.userId == userId) {
                              if (ProviderUseCase.deleteVehicle(vehicleId)) {
                                  call.respond(HttpStatusCode.OK, "Vehicle deleted")
                              } else {
                                  call.respond(HttpStatusCode.InternalServerError)
                              }
                         } else {
                             call.respond(HttpStatusCode.NotFound)
                         }
                     }
                }
            }
        }
    }
}
